-- ----------------------------------------------------------------------
-- Tagname Table
-- ----------------------------------------------------------------------
INSERT INTO Tagname (Tagname, TagnameDescription, Units, Tables, Synonyms, Keywords, Examples, Comments, Notes)
VALUES ('AAA', 'amino acids, total aromatic', 'mg', 'USDA 523, EA, SWD', NULL, NULL, NULL, 'The total value is the sum of phenylalanine plus tyrosine only, in spite of the fact that tryptophan is also chemically aromatic.', NULL)
   ('AAE-', 'amino acids, total essential; unknown or variable which amino acids are included in the total', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('AAE10A', 'amino acids, total essential; includes the eight basic essential amino acids plus arginine and histidine', 'mg', NULL, NULL, NULL, NULL, 'Arginine and histidine are included in this definition of essential amino acids because they are essential for infants.', NULL)
   ('AAE10B', 'amino acids, total essential; includes the eight basic essential amino acids plus cystine and tyrosine', 'mg', 'MW', NULL, NULL, NULL, 'Cystine and tyrosine are included in this definition of essential amino acids because of their sparing effects on the requirements for methionine and phenylalanine respectively.', NULL)
   ('AAE12', 'amino acids, total essential; includes the eight basic essential amino acids plus arginine, histidine, cystine, and tyrosine', 'mg', 'ETH, NE, EA', NULL, NULL, NULL, 'Arginine and histidine are included in this definition of essential amino acids because they are essential for infants.  Cystine and tyrosine are included because of their sparing effects on the requirements for methionine and phenylalanine respectively.', NULL)
   ('AAE8', 'amino acids, total essential; includes the eight basic essential amino acids: isoleucine, leucine, lysine, methionine, phenylalanine, threonine, tryptophan, and valine', 'mg', NULL, NULL, NULL, NULL, 'These eight amino acids are included in all definitions of the essential amino acids for man.', NULL)
   ('AAS', 'amino acids, total sulphur-containing', 'mg', 'USDA 522, NE, EA, SWD', NULL, NULL, NULL, 'The total value is the sum of cystine plus methionine.', NULL)
   ('AAT-', 'amino acids, total, precise definition not specified', 'mg', 'SFK, ETH, NE, EA', NULL, NULL, NULL, 'When total amino acids are reported, they are usually the sum of whatever amino acids were analysed for that particular food.  Consequently, this term is not precisely defined.  Additional tagnames will be introduced when precise definitions exist.  See page ? for additional discussion.', NULL)
   ('ACEAC', 'acetic acid', 'mg', 'USDA 230, SFK', NULL, NULL, NULL, NULL, NULL)
   ('AG', 'silver', 'mcg', 'USDA 378', NULL, NULL, NULL, NULL, NULL)
   ('AGAR', 'agar-agar', 'g', NULL, 'agar', NULL, NULL, NULL, NULL)
   ('AL', 'aluminium', 'mcg', 'USDA 348, SFK', 'aluminum', NULL, NULL, NULL, NULL)
   ('ALA', 'alanine', 'mg', 'USDA 513, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-alanine.', NULL)
   ('ALBU', 'albumin', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('ALC', 'alcohol', 'g', 'USDA 221, MW, DAN', 'ethanol; ethyl alcohol', NULL, NULL, NULL, NULL)
   ('ALGL', 'albumin and globulin', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('ALGNT', 'alginates', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('AMMON', 'ammonia', 'mg', 'USDA 519', NULL, NULL, NULL, NULL, NULL)
   ('AMYP', 'amylopectin', 'g', 'USDA 219', NULL, NULL, NULL, NULL, NULL)
   ('AMYPM', 'amylopectin; expressed in monosaccharide equivalents', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('AMYS', 'amylose', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('AMYSM', 'amylose; expressed in monosaccharide equivalents', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('ARAFB', 'arabinose in dietary fibre', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('ARAN', 'arabinan', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('ARAS', 'arabinose', 'g', 'SFK', NULL, NULL, NULL, 'L-arabinose only; includes only the free monosaccharide.', NULL)
   ('ARG', 'arginine', 'mg', 'USDA 511, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-arginine.', NULL)
   ('AS', 'arsenic', 'mcg', 'USDA 350', NULL, NULL, NULL, NULL, NULL)
   ('ASCDL', 'L-dehydroascorbic acid', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('ASCL', 'L-ascorbic acid', 'mg', 'USDA 402, SWD', NULL, NULL, NULL, NULL, NULL)
   ('ASH', 'ash', 'g', 'USDA 207, SKF, ETH, EGP, IND, NE, EA, PRC, DAN, SWD', 'minerals', NULL, NULL, NULL, NULL)
   ('ASN', 'asparagine', 'mg', 'USDA 525, SFK', NULL, NULL, NULL, 'Includes only L-asparagine.', NULL)
   ('ASP', 'aspartic acid', 'mg', 'USDA 514, SFK, ETH, NE, EA, DAN, SWD', 'aspartate', NULL, NULL, 'Includes only L-aspartic acid.', NULL)
   ('AU', 'gold', 'mcg', 'USDA 363', NULL, NULL, NULL, NULL, NULL)
   ('AVED5', 'delta 5-avenasterol', 'mg', 'USDA 649, SFK, FRN', 'delta 5-avenastenol', NULL, NULL, NULL, NULL)
   ('AVED7', 'delta 7-avenasterol', 'mg', 'USDA 648, SFK, FRN', 'avenasterol; delta 7-avenastenol', NULL, NULL, NULL, NULL)
   ('B', 'boron', 'mcg', 'USDA 354, SFK, PRC', NULL, NULL, NULL, NULL, NULL)
   ('BA', 'barium', 'mcg', 'USDA 351', NULL, NULL, NULL, NULL, NULL)
   ('BENAC', 'benzoic acid', 'mg', 'USDA 232, SFK', NULL, NULL, NULL, NULL, NULL)
   ('BETN', 'Betaine', 'mg', 'USDA 454', NULL, NULL, NULL, NULL, NULL)
   ('BIOT', 'biotin', 'mcg', 'USDA 416, SFK, MW, DAN, SWD', 'vitamin H', NULL, NULL, NULL, NULL)
   ('BRASTR', 'brassicasterol', 'mg', 'USDA 640, SFK, FRN', NULL, NULL, NULL, NULL, NULL)
   ('BRD', 'bromide', 'mcg', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('CA', 'calcium', 'mg', 'USDA 301, SFK, MW, ETH, EGP, IND, NE, EA, PRC, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('CAFFN', 'caffeine', 'mg', 'USDA 262, SFK', NULL, NULL, NULL, NULL, NULL)
   ('CAMD5', 'delta 5-campesterol', 'mg', 'USDA 639, SFK, FRN', 'campesterol; delta 5- campestenol', NULL, NULL, NULL, NULL)
   ('CAMD7', 'delta 7-campesterol', 'mg', 'FRN', 'delta 7-campestenol', NULL, NULL, NULL, NULL)
   ('CARGN', 'carageenan', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('CAROT', 'carotene, total', 'mcg', 'SFK, MW, PRC', 'vitamin A precursors', NULL, NULL, 'All-trans carotene only.', NULL)
   ('CARTA', 'alpha-carotene', 'mcg', 'USDA 322', NULL, NULL, NULL, 'All-trans alpha-carotene only.', NULL)
   ('CARTB', 'beta-carotene', 'mcg', 'USDA 321, DAN', NULL, NULL, NULL, 'All-trans beta-carotene only.', NULL)
   ('CARTBEQ', 'beta-carotene equivalents', 'mcg', 'USDA 320, NE, EA', 'provitamin A carotenoids', NULL, NULL, 'This value is the sum of the beta-carotene plus 1/2 the quantity of the other carotenoids with vitamin A activity.', NULL)
   ('CARTG', 'gamma-carotene', 'mcg', 'USDA 332', NULL, NULL, NULL, 'All-trans gamma-carotene only.', NULL)
   ('CASN', 'casein', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('CD', 'cadmium', 'mcg', 'USDA 356', NULL, NULL, NULL, NULL, NULL)
   ('CELLO', 'cellobiose', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('CELLU', 'cellulose', 'g', 'USDA 225, SFK, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('CHLNP', 'phosphatidyl choline', 'g', 'USDA 662, SFK', 'lecithin', NULL, NULL, NULL, NULL)
   ('CHLRAC', 'chlorogenic acid', 'mg', 'USDA 234, SFK', NULL, NULL, NULL, NULL, NULL)
   ('CHO-', 'carbohydrate, total; method of determination unknown or variable', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('CHOAVL', 'carbohydrate, available', 'g', 'SFK', NULL, NULL, NULL, 'This value includes the free sugars plus dextrins, starch, and glycogen.', NULL)
   ('CHOAVLM', 'carbohydrate, available; expressed in monosaccharide equivalents', 'g', 'MW', NULL, NULL, NULL, 'This value includes the free sugars plus dextrins, starch, and glycogen.', NULL)
   ('CHOCAL', 'cholecalciferol', 'mcg', 'DAN', 'vitamin D-3', NULL, NULL, 'Naturally occurring form.', NULL)
   ('CHOCDF', 'carbohydrate, total; calculated by difference', 'g', 'USDA 205, ETH, EGP, IND, NE, EA, DAN, SWD', NULL, NULL, NULL, 'This value is calculated using the following formula: 100 g minus total grams of water, protein, fat, and ash', 'This is not the preferred method of calculating total carbohydrate. Calculation by summation is preferred.')
   ('CHOCSM', 'carbohydrate, total; calculated by summation', 'g', 'USDA 254', NULL, NULL, NULL, 'This value is the sum of the sugars, starches, oligosaccharides, and carbohydrate dietary fibre.', NULL)
   ('CHOL-', 'cholesterol; method of determination unknown or variable', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('CHOLC', 'cholesterol; determined by chemical method (classical)', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('CHOLE', 'cholesterol; determined by enzymatic or chromatographic method', 'mg', 'MW', NULL, NULL, NULL, NULL, NULL)
   ('CHOLM', '24-methylcholest-7-erol', 'mg', 'USDA 651, SFK, FRN', NULL, NULL, NULL, NULL, NULL)
   ('CHOLME', '24-methylene cholesterol', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('CHOLN', 'choline, total', 'mg', 'USDA 421, SFK, IND', NULL, NULL, NULL, NULL, NULL)
   ('CHOLNF', 'choline, free', 'mg', 'USDA 450', NULL, NULL, NULL, NULL, NULL)
   ('CHOLNGPC', 'Choline from glycerophosphocholine', 'mg', 'USDA 453', NULL, NULL, NULL, NULL, NULL)
   ('CHOLNPC', 'Choline from phosphocholine', 'mg', 'USDA 451', NULL, NULL, NULL, NULL, NULL)
   ('CHOLNPTC', 'choline from phosphatidylcholine', 'mg', 'USDA 452', NULL, NULL, NULL, NULL, NULL)
   ('CHOLNSM', 'Choline from sphingomyelin', 'mg', 'USDA 455', NULL, NULL, NULL, NULL, NULL)
   ('CITAC', 'citric acid', 'mg', 'USDA 236, SFK', NULL, NULL, NULL, NULL, NULL)
   ('CLD', 'chloride', 'mg', 'USDA 302, SFK, MW, IND, PRC', 'chlorine', NULL, NULL, NULL, 'If the value is expressed in millimoles, mmol must be explicitly stated with the secondary tagname <UNIT/>.')
   ('CO', 'cobalt', 'mcg', 'USDA 311, SFK, IND, EA, PRC', NULL, NULL, NULL, NULL, NULL)
   ('COLG', 'collagen', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('CONPRO', 'connective tissue protein', 'mg', 'SFK', NULL, NULL, NULL, 'This term is not precisely defined in the table in which it appears.  The tagname should be construed as ``connective tissue protein as the term is used by Souci- Fachmann-Kraut\'\'.', NULL)
   ('CR', 'chromium', 'mcg', 'USDA 310, SFK, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('CREATN', 'creatinine', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('CRYPX', 'cryptoxanthin', 'mcg', 'USDA 334', NULL, NULL, NULL, NULL, NULL)
   ('CU', 'copper', 'mg', 'USDA 312, SFK, MW, EA, PRC, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('CYAN', 'Cyanide', 'mcg', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('CYS', 'cystine', 'mg', 'USDA 507, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Cysteine is often the natural form, which is converted to cystine during chromatography; includes only the L-amino acid.', NULL)
   ('DAIDZN', 'daidzin', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('DAIDZNA', 'acetyl-daidzin', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('DAIDZNM', 'malonyl-daidzin', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('DDZEIN', 'daidzein', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('DEXTN', 'dextrins', 'g', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('DEXTNM', 'dextrins; expressed in monosaccharide equivalents', 'g', 'MW', NULL, NULL, NULL, NULL, NULL)
   ('DGLY', 'diglycerides, total', 'g', 'USDA 656', NULL, NULL, NULL, NULL, NULL)
   ('DISAC', 'disaccharides, total', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('DISACM', 'disaccharides, total; expressed in monosaccharide equivalents', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('DM', 'dry matter', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('DOPN', 'dopamine', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('ENER-', 'energy; method of determination unknown or variable', 'kJ.  The value for <ENER-> may be expressed in kilocalories instead of the default unit of kilojoules. However, if expressed in kilocalories, kcal must be explicitly stated with the secondary tagname <UNIT/>.', NULL, 'kilojoules; kilocalories; Calories; food energy', NULL, NULL, NULL, 'It would be confusing and would imply additional information that does not exist if two <ENER-> values, i.e., one expressed in kilocalories and the other expressed in kilojoules, were included for a single food item when one value has simply been calculated from the other using the conversion equation: 1 kcal = 4.184 kJ.  Consequently, one or the other should be used, but not both.')
   ('ENERA', 'energy, gross; determined by direct analysis using bomb calorimetry', 'kJ.  The value for <ENERA> may be expressed in kilocalories instead of the default unit of kilojoules. However, if expressed in kilocalories, kcal must be explicitly stated with the secondary tagname <UNIT/>.', NULL, 'kilojoules; kilocalories; Calories; food energy', NULL, NULL, NULL, 'It would be confusing and would imply additional information that does not exist if two <ENERA> values, i.e., one expressed in kilocalories and the other expressed in kilojoules, were included for a single food item when one value has simply been calculated from the other using the conversion equation: 1 kcal = 4.184 kJ. Consequently, one or the other should be used, but not both.')
   ('ENERC', 'energy, total metabolizable; calculated from the energy-producing food components', 'kJ.  The value for <ENERC> may be expressed in kilocalories instead of the default unit of kilojoules. However, if expressed in kilocalories, kcal must be explicitly stated with the secondary tagname <UNIT/>.', 'MW STDA  standard conversion factors originally derived by Atwater using available carbohydrate kilocalories = (4 x g total protein) + (3.75 x g available carbohydrate expressed as monosaccharides) + (9 x g total fat) + (7 x g alcohol) Tables: MW STDT  standard conversion factors originally derived by Atwater using total carbohydrate kilocalories = (4 x g total protein) + (4 x g total carbohydrate) + (9 x g total fat) + (7 x g alcohol) Tables: EGP, IND CDXC  CODEX conversion factors for nutritional labelling of total kilocalories kilocalories = (4 x g total protein) + (4 x g total carbohydrate) + (9 x g total fat) + (7 x g alcohol) + (3 x g organic acid) CDXJ  CODEX conversion factors for nutritional labelling of total kilojoules kilojoules = (17 x g total protein) + (17 x g total carbohydrate) + (37 x g total fat) + (29 x g alcohol) + (13 x g organic acid) FDS  conversion factors based on type of food as reported in World Health Organization Technical Report Series No. 522 (?) and the United States Department of Agriculture Handbooks No. 8 (?) and No. 74 (?). Tables: USDA 208 and 268, ETH, NE, EA', 'kilojoules; kilocalories; Calories; food energy', 'Following are the available keywords to describe the conversion factors that were used for calculating total metabolizable energy: KJA  kilojoule conversion factors using available carbohydrate kilojoules = (17 x g total protein) + (16 x g available carbohydrate expressed as monosaccharides) + (37 x g total fat) + (29 x g alcohol)', 'The 76 kcal/100 g energy value for whole cow\'s milk in the Ethiopian food table was calculated from proximate values using conversion factors from the USDA Agriculture Handbook No. 8.  Therefore, the energy value would be listed using the <ENERC> tagname and the USDA keyword, with the kilocalorie unit stated with the secondary tagname <UNIT/> to replace the default unit of kilojoules: <ENERC> 76 USDA <UNIT/> kcal </UNIT/> </ENERC> The 272 kJ/100 g energy value for fresh, whole cow\'s milk in the McCance and Widdowson food table was calculated with the kilojoule conversion factors that use available carbohydrate.  Therefore, the energy value would be listed using the <ENERC> tagname and the KJA keyword: <ENERC> 272 KJA </ENERC> If an energy value expressed in kilocalories were calculated for whole cow\'s milk using conversion factors for protein, fat, and total carbohydrate, and these conversion factors did not conform to any of the factors described by the available keywords, the energy value would be listed using the <ENERC> tagname and the <XP>, <XF> and <XCT> secondary tagnames.  The kilocalorie unit would be stated with the secondary tagname <UNIT/> to replace the default unit of kilojoules: <ENERC> 76.42 <XP> 4.3 <XF> 8.8 <XCT> 3.9 <UNIT/> kcal </UNIT/> </ENERC>', 'In addition to a value for the quantity of total metabolizable energy, <ENERC> includes a description or listing of the conversion factors used to calculate this energy value from the proximate quantities.  The conversion factors may be described by a keyword, or the conversion factors may be listed using secondary tagnames within <ENERC>.  (More than one <ENERC> tagname may exist for a single food item if the values were calculated from the proximate components using different conversion factors.)', 'In these examples, </UNIT/> and </ENERC> are end-tags required in interchange format to indicate the end of the unit and energy information.  See the INFOODS Data Interchange Handbook for details on interchange format.')
   ('ERGCAL', 'ergocalciferol', 'mcg', NULL, 'vitamin D-2', NULL, NULL, NULL, NULL)
   ('ETHAM', 'ethanolamines, total', 'g', 'SFK Saturated Fatty Acids', NULL, NULL, NULL, NULL, NULL)
   ('F10D0', 'fatty acid 10:0', 'g', 'USDA 610, SFK, PRC, FRN, DAN, SWD', 'capric acid; decanoic acid', NULL, NULL, NULL, NULL)
   ('F10D1', 'fatty acid 10:1', 'g', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('F12D0', 'fatty acid 12:0', 'g', 'USDA 611, SFK, NE, PRC, FRN, DAN, SWD', 'lauric acid; dodecanoic acid', NULL, NULL, NULL, NULL)
   ('F12D1', 'fatty acid 12:1', 'g', 'FRN', 'lauroleic acid', NULL, NULL, NULL, NULL)
   ('F13D0', 'fatty acid 13:0', 'g', 'USDA 696, FRN', 'tridecanoic acid', NULL, NULL, NULL, NULL)
   ('F14D0', 'fatty acid 14:0', 'g', 'USDA 612, SFK, NE, PRC, FRN, DAN, SWD', 'myristic acid; tetradecanoic acid', NULL, NULL, NULL, NULL)
   ('F14D1', 'fatty acid 14:1', 'g', 'USDA 625, PRC, FRN, DAN', 'myristoleic acid; tetradecenoic acid', NULL, NULL, NULL, NULL)
   ('F15D0', 'fatty acid 15:0', 'g', 'USDA 652, PRC, FRN, DAN', 'pentadecylic acid; pentadecanoic acid', NULL, NULL, NULL, NULL)
   ('F15D1', 'fatty acid 15:1', 'g', 'FRN, DAN', 'pentadecenoic acid', NULL, NULL, NULL, NULL)
   ('F15D1N9', 'fatty acid 15:1 n-9', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F16D0', 'fatty acid 16:0', 'g', 'USDA 613, SFK, NE, EA, PRC, FRN, DAN, SWD', 'palmitic acid; hexadecanoic acid', NULL, NULL, NULL, NULL)
   ('F16D1', 'fatty acid 16:1', 'g', 'USDA 626, SFK, NE, PRC, FRN, DAN, SWD', 'palmitoleic acid; hexadecenoic acid', NULL, NULL, NULL, NULL)
   ('F16D1C', 'fatty acid cis 16:1', 'g', 'USDA 673', NULL, NULL, NULL, NULL, NULL)
   ('F16D1T', 'fatty acid trans 16:1', 'g', 'USDA 662', NULL, NULL, NULL, NULL, NULL)
   ('F16D2N4', 'fatty acid 16:2 n-4', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F16D2N7', 'fatty acid 16:2 n-7', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F16D3N3', 'fatty acid 16:3 n-3', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F16D3N4', 'fatty acid 16:3 n-4', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F16D4N1', 'fatty acid 16:4 n-1', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F16D4N4', 'fatty acid 16:4 n-4', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F17D0', 'fatty acid 17:0', 'g', 'USDA 653, SFK, PRC, FRN, DAN', 'margaric acid; heptadecanoic acid', NULL, NULL, NULL, NULL)
   ('F17D1', 'fatty acid 17:1', 'g', 'USDA 687, FRN, DAN', 'heptadecenoic acid', NULL, NULL, NULL, NULL)
   ('F18D0', 'fatty acid 18:0', 'g', 'USDA 614, SFK, NE, EA, PRC, FRN, DAN, SWD', 'stearic acid; octadecanoic acid', NULL, NULL, NULL, NULL)
   ('F18D1', 'fatty acid 18:1', 'g', 'USDA 617, FRN, DAN, SWD', 'oleic acid; octadecenoic acid', NULL, NULL, NULL, NULL)
   ('F18D1C', 'fatty acid cis 18:1', 'g', 'USDA 674', NULL, NULL, NULL, NULL, NULL)
   ('F18D1CN9', 'fatty acid 18:1 cis n-9', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F18D1N7', 'fatty acid 18:1 n-7', 'g', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('F18D1N9', 'fatty acid 18:1 n-9', 'g', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('F18D1T', 'fatty acid trans 18:1', 'g', 'USDA 663', NULL, NULL, NULL, NULL, NULL)
   ('F18D1TN9', 'fatty acid trans 18:1 n-9', 'g', 'SFK, NE, EA, FRN', 'elaidic acid; octadecenoic acid', NULL, NULL, NULL, NULL)
   ('F18D2', 'fatty acid 18:2', 'g', 'USDA 618, NZ', NULL, NULL, NULL, NULL, NULL)
   ('F18D2CN3', 'fatty acid 18:2cis n-3', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F18D2CN6', 'fatty acid cis,cis 18:2 n-6', 'g', 'USDA 675, SFK, NE, EA, PRC, FRN, DAN, SWD', 'linoleic acid; octadecadienoic acid', NULL, NULL, NULL, NULL)
   ('F18D2N4', 'fatty acid 18:2 n-4', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F18D2N6', 'fatty acid 18:2, n-6', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F18D2N9', 'fatty acid 18:2 n-9', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F18D2TN6', 'fatty acid 18:2trans n-6', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F18D3', 'fatty acid 18:3', 'g', 'USDA 619, NZ', NULL, NULL, NULL, NULL, NULL)
   ('F18D3CN3', 'fatty acid cis, cis, cis 18:3 n-3', 'g', 'USDA 851', NULL, NULL, NULL, NULL, NULL)
   ('F18D3N3', 'fatty acid 18:3 n-3', 'g', 'SFK, NE, EA, PRC, FRN, DAN, SWD', 'alpha-linolenic acid; octadecatrienoic acid', NULL, NULL, NULL, NULL)
   ('F18D3N6', 'fatty acid 18:3 n-6', 'g', 'FRN', 'gamma-linolenic acid', NULL, NULL, NULL, NULL)
   ('F18D4', 'fatty acid 18:4', 'g', 'USDA 627, NE, FRN', 'parinaric acid; stearidonic acid; octadecatetraenoic acid', NULL, NULL, NULL, NULL)
   ('F18D4N3', 'fatty acid 18:4 n-3', 'g', 'FRN', NULL, NULL, NULL, NULL, NULL)
   ('F19D0', 'fatty acid 19:0', 'g', NULL, 'nonadecanoic acid', NULL, NULL, NULL, NULL)
   ('F19D1N7', 'fatty acid 19:1 n-7', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F20D0', 'fatty acid 20:0', 'g', 'USDA 615, SFK, PRC, FRN, DAN, SWD', 'arachidic acid; eicosanoic acid', NULL, NULL, NULL, NULL)
   ('F20D1', 'fatty acid 20:1', 'g', 'USDA 628, NE, PRC, FRN, DAN, SWD', 'gadoleic acid; eicosenoic acid', NULL, NULL, NULL, NULL)
   ('F20D1N11', 'fatty acid 20:1 n-11', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F20D1N7', 'fatty acid 20:1 n-7', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F20D1N9', 'fatty acid 20:1 n-9', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F20D2', 'fatty acid 20:2', 'g', 'PRC, FRN', 'eicosadienoic acid', NULL, NULL, NULL, NULL)
   ('F20D2CN6', 'fatty acid cis, cis 20:2 n-6', 'g', 'USDA 672', NULL, NULL, NULL, NULL, NULL)
   ('F20D2N6', 'fatty acid 20:2 n-6', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F20D3', 'fatty acid 20:3', 'g', 'USDA 689, FRN, DAN', 'eicosatrienoic acid', NULL, NULL, NULL, NULL)
   ('F20D3N3', 'fatty acid 20:3 n-3', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F20D3N6', 'fatty acid 20:3 n-6', 'g', 'USDA 853', 'homogammalinolenic', NULL, NULL, NULL, NULL)
   ('F20D3N9', 'fatty acid 20:3 n-9', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F20D4', 'fatty acid 20:4', 'g', 'USDA 620, FRN', 'arachidonic acid', NULL, NULL, NULL, NULL)
   ('F20D4N3', 'fatty acid 20:4 n-3', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F20D4N6', 'fatty acid 20:4 n-6', 'g', 'USDA 855, SFK, NE, PRC, FRN, DAN, SWD', 'arachidonic acid; eicosatetraenoic acid', NULL, NULL, NULL, NULL)
   ('F20D5', 'fatty acid 20:5', 'g', 'FRN', 'eicosapentaenoic acid', NULL, NULL, NULL, NULL)
   ('F20D5N3', 'fatty acid 20:5 n-3', 'g', 'USDA 629, NE, FRN, DAN, SWD', 'eicosapentaenoic acid; EPA; timnodonic acid', NULL, NULL, NULL, NULL)
   ('F21D0', 'fatty acid 21:0', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F21D5N3', 'fatty acid 21:5 n-3', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F22D0', 'fatty acid 22:0', 'g', 'USDA 624, SFK, PRC, FRN, DAN, SWD', 'behenic acid; docosanoic acid', NULL, NULL, NULL, NULL)
   ('F22D1', 'fatty acid 22:1', 'g', 'USDA 630, NE, PRC, FRN, DAN, SWD, NZ', 'erucic acid; cetoleic acid; docosenoic acid', NULL, NULL, NULL, NULL)
   ('F22D1CN11', 'fatty acid cis 22:1 n-11', 'g', NULL, 'cetoleic acid, 11-docosenoic acid', NULL, NULL, NULL, NULL)
   ('F22D1CN9', 'fatty acid cis 22:1 n-9', 'g', 'SFK, FRN, SWD', 'erucic acid; docosenoic acid', NULL, NULL, NULL, NULL)
   ('F22D1N9', 'fatty acid 22:1 n-9', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F22D1TN9', 'fatty acid trans 22:1 n-9', 'g', 'FRN', 'brassidic acid', NULL, NULL, NULL, NULL)
   ('F22D2', 'fatty acid 22:2', 'g', 'FRN', 'docosadienoic acid', NULL, NULL, NULL, NULL)
   ('F22D3', 'fatty acid 22:3', 'g', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('F22D4', 'fatty acid 22:4', 'g', 'FRN', 'docosatetraenoic acid', NULL, NULL, NULL, NULL)
   ('F22D4N3', 'fatty acid 22:4 n-3', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F22D5', 'fatty acid 22:5', 'g', 'FRN', 'docosapentaenoic acid', NULL, NULL, NULL, NULL)
   ('F22D5N3', 'fatty acid 22:5 n-3', 'g', 'USDA 631, NE, PRC, FRN, DAN, SWD', 'docosapentaenoic acid', NULL, NULL, NULL, NULL)
   ('F22D5N6', 'fatty acid 22:5 n-6', 'g', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('F22D6', 'fatty acid 22:6', 'g', 'FRN', 'docosahexaenoic acid', NULL, NULL, NULL, NULL)
   ('F22D6N3', 'fatty acid 22:6 n-3', 'g', 'USDA 621, NE, PRC, FRN, DAN, SWD', 'docosahexaenoic acid; DHA', NULL, NULL, NULL, NULL)
   ('F23D0', 'fatty acid 23:0', 'g', 'FRN', 'tricosanoic acid', NULL, NULL, NULL, NULL)
   ('F23D1', 'fatty acid 23:1', 'g', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('F24D0', 'fatty acid 24:0', 'g', 'USDA 654, SFK, FRN Monounsaturated fatty acids For mono- and poly-unsaturated fatty acids, the following naming conventions are used: FnDm indicates an unspecified bond position, and potentially a mixture.  FnDmNo indicates an omega-o bond position, potentially mixed cis and trans forms.  FnDmCNo and FnDmTNo indicate values for the specific cis and trans forms respectively.', 'lignoceric acid; tetracosanoic acid', NULL, NULL, NULL, NULL)
   ('F24D1', 'fatty acid 24:1', 'g', 'FRN', 'selacholeic acid, nervonic acid, tetracosenoic acid', NULL, NULL, NULL, NULL)
   ('F24D1C', 'fatty acid cis 24:1', 'g', 'USDA 671 Polyunsaturated fatty acids For naming conventions, see monounsaturated fatty acids, above.', NULL, NULL, NULL, NULL, NULL)
   ('F24D6', 'fatty acid 24:6', 'g', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('F4D0', 'fatty acid 4:0', 'g', 'USDA 607, SFK, FRN, DAN, SWD', 'butyric acid; tetranoic acid; butanoic acid', NULL, NULL, NULL, NULL)
   ('F5D0', 'fatty acid 5:0', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('F6D0', 'fatty acid 6:0', 'g', 'USDA 608, SFK, PRC, FRN, DAN, SWD', 'caproic acid; hexanoic acid', NULL, NULL, NULL, NULL)
   ('F8D0', 'fatty acid 8:0', 'g', 'USDA 609, SFK, PRC, FRN, DAN, SWD', 'caprylic acid; octanoic acid', NULL, NULL, NULL, NULL)
   ('FACID', 'fatty acids, total', 'g', NULL, NULL, 'The available keywords for those tables that list the conversion factors for calculating total fatty acids from total fat are: MW  McCance and Widdowson (?) USDA  USDA Handbook No. 8 (?) The secondary tagname for identifying a specific fatty acid conversion factor is: <XFA>  conversion factor for calculating total fatty acids from total fat.', NULL, 'Two data items are required for tagname <FACID>:  the total quantity of fatty acids and identification of the conversion factor used to calculate this value from the quantity of total fat.  If the conversion factor was taken from a table in one of the sources identified by the keywords listed below, the keyword should be used during data interchange.  Otherwise, the conversion factor can be explicitly stated within a secondary tagname.  It is also acceptable to include both a keyword and the specific conversion factor in the data.', NULL)
   ('FADT', 'fatty acids, total double trans', 'g', NULL, NULL, NULL, NULL, 'Some countries are planning actions to limit these acids (not single trans) from foods, e.g., chocolate.', NULL)
   ('FAESS', 'fatty acids, total essential', 'g', 'FRN', NULL, NULL, NULL, 'This value is the sum of linoleic acid, linolenic acid, and arachidonic acid.', NULL)
   ('FAFRE', 'fatty acids, total free', 'g', 'USDA 658', NULL, NULL, NULL, NULL, NULL)
   ('FAMS', 'fatty acids, total monounsaturated', 'g', 'USDA 645, NE, FRN, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('FAPU', 'fatty acids, total polyunsaturated', 'g', 'USDA 646, IND, NE, FRN, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('FAPUN3', 'fatty acids, total n-3 polyunsaturated', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('FAPUN6', 'fatty acids, total n-6 polyunsaturated', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('FASAT', 'fatty acids, total saturated', 'g', 'USDA 606, SFK, NE, EA, FRN, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('FAT', 'fat, total', 'g', 'USDA 204, SFK, MW, ETH, EGP, IND, NE, EA, PRC, FRN, DAN, SWD', 'total lipid', NULL, NULL, NULL, NULL)
   ('FATCE', 'fat, total; derived by analysis using continuous extraction', 'g', NULL, NULL, NULL, NULL, 'The Soxhlet method has often been used to analyse for total fat using continuous extraction.  This method tends to underestimate the total fat value of a food.', NULL)
   ('FATNLEA', 'total fat by NLEA definition (triglyceride equivalents of fatty acids)', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('FATRN', 'fatty acids, total trans', 'g', 'USDA 605', NULL, NULL, NULL, NULL, NULL)
   ('FATRNM', 'fatty acids, total trans-monoenoic', 'g', 'USDA 693', NULL, NULL, NULL, NULL, NULL)
   ('FATRNP', 'fatty acids, total trans-polyenoic', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('FD', 'fluoride', 'mcg', 'USDA 313, SFK, EA, SWD', 'fluorine', NULL, NULL, NULL, NULL)
   ('FE', 'iron, total', 'mg', 'USDA 303, SFK, MW, ETH, IND, NE, EA, PRC, DAN, SWD', NULL, NULL, NULL, 'Includes both haem and non- haem iron.', NULL)
   ('FERAC', 'ferulic acid', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('FIB-', 'fibre; method of determination unknown or variable', 'g', NULL, NULL, NULL, NULL, NULL, 'Tagname <FIB-> is used to identify fibre values which represent unknown fibre components or which were obtained by unknown methods or a mixture of methods.')
   ('FIBAD', 'fibre; determined by acid detergent method', 'g', NULL, NULL, NULL, NULL, 'Includes cellulose, lignin, and some hemicelluloses.', NULL)
   ('FIBADC', 'fibre, acid detergent method, Clancy modification.', 'g', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('FIBC', 'fibre, crude', 'g', 'USDA 206, SFK, ETH, EGP', NULL, NULL, NULL, 'The crude fibre method of fibre analysis is obsolete.', NULL)
   ('FIBHEX', 'hexoses in dietary fibre', 'g', 'DAN', NULL, NULL, NULL, NULL, NULL)
   ('FIBINS', 'fibre, water-insoluble', 'g', 'SFK, MW', NULL, NULL, NULL, 'Sum of insoluble components from the AOAC total dietary fibre method; includes primarily lignin, cellulose, and most of the hemicellulose.', 'Values for <FIBINS> may also be obtained by subtracting soluble fibre from total dietary fibre, i.e., by subtracting the value of <FIBSOL> from the value of <FIBTG>.')
   ('FIBND', 'fibre; determined by neutral detergent method', 'g', 'USDA 273', NULL, NULL, NULL, 'Includes lignin, cellulose, and insoluble hemicellulose.', NULL)
   ('FIBPEN', 'pentoses in dietary fibre', 'g', 'USDA 223, DAN', NULL, NULL, NULL, NULL, NULL)
   ('FIBSOL', 'fibre, water-soluble', 'g', 'SFK', NULL, NULL, NULL, 'Sum of soluble components from the AOAC total dietary fibre method; includes primarily algal polysaccharides, gums, pectins, and mucilages.', NULL)
   ('FIBTG', 'fibre, total dietary; determined gravimetrically by the AOAC total dietary fibre method', 'g', 'SFK', NULL, NULL, NULL, 'Sum of the water-soluble components and the water-insoluble components of dietary fibre; can be calculated by adding the values of <FIBSOL> and <FIBINS>; includes all non- starch polysaccharides and lignin.', NULL)
   ('FIBTS', 'fibre, total dietary; sum of non- starch polysaccharide components and lignin', 'g', NULL, NULL, NULL, NULL, 'Sum of the polysaccharide components of dietary fibre measured sequentially on the same sample (for example, by using the Southgate colorimetric procedure) plus lignin measured gravimetrically.', NULL)
   ('FIBTSW', 'fibre, total dietary; Wenlock modification', 'g', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('FOL', 'folate, total', 'mcg', 'USDA 417, SFK, MW, ETH, IND, EA, DAN, SWD', 'folacin; folic acid', NULL, NULL, 'Includes both conjugated and free folate.', NULL)
   ('FOLAC', 'folic acid, synthetic folic acid', 'mcg', 'USDA 431', NULL, NULL, NULL, NULL, NULL)
   ('FOLDFE', 'folate, dietary folate equivalents', 'mcg DFE', 'USDA 435', NULL, NULL, NULL, 'folate total = mcg food folate + (1.7 X mcg folic acid)', NULL)
   ('FOLFD', 'folate food, naturally occuring food folates', 'mcg', 'USDA 432', NULL, NULL, NULL, NULL, NULL)
   ('FOLFRE', 'folate, free', 'mcg', 'USDA 419, MW, IND, DAN', NULL, NULL, NULL, NULL, NULL)
   ('FRUFB', 'fructose in dietary fibre', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('FRUS', 'fructose', 'g', 'USDA 212, SFK, DAN, SWD', NULL, NULL, NULL, 'D-fructose only; includes only the free monosaccharide.', NULL)
   ('FRUTN', 'fructan', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('FUCSTR28', '28-iso-fucosterol', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('FUMAC', 'fumaric acid', 'mg', 'USDA 237, SFK', NULL, NULL, NULL, NULL, NULL)
   ('GALAAC', 'galacturonic acid', 'mg', 'USDA 238, SFK', NULL, NULL, NULL, NULL, NULL)
   ('GALFB', 'galactose in dietary fibre', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GALLAC', 'gallic acid', 'mg', 'USDA 239, SFK', NULL, NULL, NULL, NULL, NULL)
   ('GALS', 'galactose', 'g', 'SFK', NULL, NULL, NULL, 'Includes only the free monosaccharide.', NULL)
   ('GALTN', 'galactan', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLN', 'glutamine', 'mg', 'SFK', NULL, NULL, NULL, 'Includes only L-glutamine.', NULL)
   ('GLOB', 'globulin', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLU', 'glutamic acid', 'mg', 'USDA 515, SFK, ETH, NE, EA, DAN, SWD', 'glutamate', NULL, NULL, 'Includes only L-glutamic acid.', NULL)
   ('GLUAKAC', 'alpha-keto-glutaric acid', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('GLUCAC', 'gluconic acid', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('GLUCNB', 'betaglucan', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLUFB', 'glucose in dietary fibre', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLUMN', 'glucomannan', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLUS', 'glucose', 'g', 'USDA 211, SFK, DAN, SWD', NULL, NULL, NULL, 'D-glucose only; includes only the free monosaccharide.', NULL)
   ('GLUTN', 'gluten', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLY', 'glycine', 'mg', 'USDA 516, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-glycine.', NULL)
   ('GLYC', 'glycogen', 'g', 'USDA 272, SFK', NULL, NULL, NULL, NULL, NULL)
   ('GLYCER-', 'glycerides, total; method of determination unknown or variable', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLYCERA', 'glycerides, total; determined by analysis', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLYCERC', 'glycerides, total; calculated from fatty acid composition', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLYCLAC', 'glycolic acid', 'mg', 'USDA 240, SFK', NULL, NULL, NULL, NULL, NULL)
   ('GLYCM', 'glycogen; expressed in monosaccharide equivalents', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLYCTEIN', 'glycitein', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLYCTN', 'glycitin', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLYCTNA', 'acetyl-glycitin', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLYCTNM', 'malonyl-glycitin', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GLYLIP', 'glycolipids, total', 'g', 'USDA 604', NULL, NULL, NULL, NULL, NULL)
   ('GLYRL', 'glycerol', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('GNSTEIN', 'genistein', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GNSTIN', 'genistin', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GNSTINA', 'acetyl-genistin', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GNSTINM', 'malonyl-genistin', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GPCHOLN', 'Glycerophosphocholine', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('GUMS', 'gums', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('HAEM', 'iron, haem', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('HEMCEL', 'hemicellulose', 'g', 'USDA 224, SFK', NULL, NULL, NULL, 'Includes hexose and pentose.', NULL)
   ('HEXSN', 'hexosan', 'g', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('HG', 'mercury', 'mcg', 'USDA 370', NULL, NULL, NULL, NULL, NULL)
   ('HIS', 'histidine', 'mg', 'USDA 512, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-histidine.', NULL)
   ('HISTN', 'histamine', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('HYP', 'hydroxyproline', 'mg', 'USDA 521, SFK', NULL, NULL, NULL, 'Includes only L- hydroxyproline.', NULL)
   ('ID', 'iodide', 'mcg', 'USDA 314, SFK, EA, PRC, DAN, SWD', 'iodine', NULL, NULL, NULL, NULL)
   ('ILE', 'isoleucine', 'mg', 'USDA 503, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-isoleucine.', NULL)
   ('INOTL', 'inositol', 'mcg', 'USDA 422, SFK', NULL, NULL, NULL, NULL, NULL)
   ('INULN', 'inulin', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('ISOCAC', 'isocitric acid', 'mg', 'USDA 241, SFK', NULL, NULL, NULL, NULL, NULL)
   ('ISOFLVND', 'total Isoflavonoids', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('K', 'potassium', 'mg', 'USDA 306, SFK, MW, IND, NE, EA, PRC, DAN, SWD', NULL, NULL, NULL, NULL, 'If the value is expressed in millimoles, mmol<NA> must be explicitly stated with the secondary tagname <UNIT/>.')
   ('LACAC', 'lactic acid', 'mg', 'USDA 242, SFK', NULL, NULL, NULL, NULL, NULL)
   ('LACS', 'lactose', 'g', 'USDA 213, SFK, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('LACSM', 'lactose; expressed in monosaccharide equivalents', 'g', 'MW', NULL, NULL, NULL, NULL, NULL)
   ('LEU', 'leucine', 'mg', 'USDA 504, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-leucine.', NULL)
   ('LI', 'lithium', 'mcg', 'USDA 368', NULL, NULL, NULL, NULL, NULL)
   ('LIGN', 'lignin', 'g', 'SFK, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('LUTN', 'lutein', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('LUTNZEA', 'lutein plus zeaxanthine', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('LYCPN', 'lycopene', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('LYS', 'lysine', 'mg', 'USDA 505, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-lysine.', NULL)
   ('MALAC', 'malic acid', 'mg', 'USDA 243, SFK', NULL, NULL, NULL, NULL, NULL)
   ('MALS', 'maltose', 'g', 'USDA 214, SFK, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('MALSM', 'maltose; expressed in monosaccharide equivalents', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('MALTRS', 'maltotriose', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('MALTRSM', 'maltotriose; expressed in monosaccharide equivalents', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('MANFB', 'mannose in dietary fibre', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('MANN', 'mannan', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('MANTL', 'mannitol', 'mg', 'USDA 260, SFK', NULL, NULL, NULL, NULL, NULL)
   ('MET', 'methionine', 'mg', 'USDA 506, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-methionine.', NULL)
   ('METH', 'methyl alcohol', 'mg', 'SFK', 'methanol', NULL, NULL, NULL, NULL)
   ('MG', 'magnesium', 'mg', 'USDA 304, SFK, MW, IND, NE, EA, PRC, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('MGLY', 'monoglycerides, total', 'g', 'USDA 655', NULL, NULL, NULL, NULL, NULL)
   ('MN', 'manganese', 'mcg', 'USDA 315, SFK, EA, PRC, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('MNSAC', 'monosaccharides, total', 'g', NULL, NULL, NULL, NULL, 'Includes only the free monosaccharides.', NULL)
   ('MO', 'molybdenum', 'mcg', 'USDA 316, SFK, EA, PRC, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('MUCIL', 'mucilages', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('NA', 'sodium', 'mg', 'USDA 307, SFK, MW, IND, NE, EA, PRC, DAN, SWD', NULL, NULL, NULL, NULL, 'If the value is expressed in millimoles, mmol must be explicitly stated with the secondary tagname <UNIT/>.')
   ('NACL', 'salt', 'mg', 'USDA 375, SFK', 'NACL', NULL, NULL, NULL, NULL)
   ('NAM', 'nitrogen, amino', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('NHAEM', 'iron, non-haem', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('NI', 'nickel', 'mcg', 'USDA 371, SFK, PRC', NULL, NULL, NULL, NULL, NULL)
   ('NIA', 'niacin, preformed', 'mg', 'USDA 406, SFK, MW, ETH, IND, NE, EA, PRC, DAN, SWD', 'nicotinic acid; nicotinamide (These terms are not true synonyms but are often used in food tables to refer to niacin.)', NULL, NULL, 'Nicotinic acid and nicotinamide.', NULL)
   ('NIAAVL', 'niacin, available', 'mg', NULL, NULL, NULL, NULL, 'total niacin minus bound niacin', NULL)
   ('NIAEQ', 'niacin equivalents, total', 'mg', 'USDA 409, DAN, SWD', NULL, NULL, NULL, 'Preformed niacin plus niacin equivalents from tryptophan.', NULL)
   ('NIATRP', 'niacin equivalents from tryptophan', 'mg', 'USDA 407 & 408, MW, DAN', NULL, NULL, NULL, '1/60 x tryptophan.', NULL)
   ('NITRA', 'nitrates', 'mg', 'USDA 264, SFK', NULL, NULL, NULL, NULL, NULL)
   ('NITRI', 'nitrites', 'mg', 'USDA 265, SFK', NULL, NULL, NULL, NULL, NULL)
   ('NITRN', 'nitrosamine, total', 'mg', 'USDA 266', NULL, NULL, NULL, NULL, NULL)
   ('NITRNN', 'nitrosamine, non-volatile', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('NITRNV', 'nitrosamine, volatile', 'mg', NULL, NULL, NULL, NULL, 'Subject of forthcoming regulations.', NULL)
   ('NNP', 'nitrogen, non-protein', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('NPRO', 'nitrogen, protein', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('NT', 'nitrogen, total', 'g', 'USDA 202, MW, ETH, EGP, IND, NE, EA', NULL, NULL, NULL, 'Determined by Kjeldahl method.', NULL)
   ('OA', 'organic acids, total', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('OLSAC', 'oligosaccharides, total available', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('OLSACM', 'oligosaccharides, total available; expressed in monosaccharide equivalents', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('OXACAC', 'oxaloacetic acid', 'mg', 'USDA 244, SFK', NULL, NULL, NULL, NULL, NULL)
   ('OXALAC', 'oxalic acid', 'mg', 'USDA 245, SFK, IND', NULL, NULL, NULL, NULL, NULL)
   ('P', 'phosphorus', 'mg', 'USDA 305, SFK, MW, ETH, EGP, IND, NE, EA, PRC, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('PANTAC', 'pantothenic acid', 'mg', 'USDA 410, SFK, MW, EA, DAN, SWD', 'D-pantothenate; vitamin B-5 (obsolete term, may still appear in some tables)', NULL, NULL, NULL, NULL)
   ('PARHBAC', 'parahydrobenzoic acid', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('PB', 'lead', 'mcg', 'USDA 367', NULL, NULL, NULL, NULL, NULL)
   ('PCHOLN', 'Phosphocholine', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('PECT', 'pectin', 'g', 'USDA 220, SFK, SWD', NULL, NULL, NULL, 'Reflects AOAC or equivalent procedure.  Polymers of galacturonic acid unspecified.', 'Additional tagnames will be added, when needed by food composition tables and data bases, to reflect the very large number of polysaccharides present in foods and, specifically, to reflect different degrees of methoxylation in pectic substances.')
   ('PENSN', 'pentosan', 'g', 'USDA 222, SFK', NULL, NULL, NULL, NULL, NULL)
   ('PHE', 'phenylalanine', 'mg', 'USDA 508, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L- phenylalanine.', NULL)
   ('PHOLIP', 'phospholipids, total', 'g', 'USDA 603', NULL, NULL, NULL, NULL, NULL)
   ('PHYSTR', 'phytosterols, total', 'mg', 'USDA 636', 'total plant sterols', NULL, NULL, 'Includes avenasterol, brassicasterol, campesterol, sitosterol, spinasterol, and stigmasterol.', NULL)
   ('PHYTAC', 'phytic acid', 'mg', 'USDA 246, SFK, MW, IND', 'phytin P', NULL, NULL, NULL, NULL)
   ('PIPN', 'piperine', 'g', 'USDA 259', NULL, NULL, NULL, NULL, NULL)
   ('PRO', 'proline', 'mg', NULL, NULL, NULL, NULL, 'Includes only L-proline.', NULL)
   ('PRO-', 'protein, total; method of determination unknown or variable', 'g', NULL, NULL, NULL, NULL, 'The <PRO-> tagname should be used for a total protein value when it is not known whether the value was the result of a direct analysis or whether it was calculated from total nitrogen, protein nitrogen, or amino nitrogen.  The <PRO-> tagname should also be used if it is known that the total protein value was calculated from one of the nitrogen components, but the conversion factor used in the calculation is unknown.', NULL)
   ('PROA', 'protein, total; determined by direct analysis', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('PROANI', 'protein from animal sources', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('PROCNA', 'protein, total; calculated from amino nitrogen', 'g', NULL, NULL, NULL, NULL, 'Two pieces of data are associated with the tagname <PROCNA>.  The first is the quantity of total protein and the second is the conversion factor used to calculate total protein from amino nitrogen.', 'The total protein found in food tables is rarely calculated from amino nitrogen.  <PROCNT> is the appropriate tagname for total protein in most cases.')
   ('PROCNP', 'protein, total; calculated from protein nitrogen', 'g', NULL, NULL, NULL, NULL, 'Two pieces of data are associated with the tagname <PROCNP>.  The first is the quantity of total protein and the second is the conversion factor used to calculate total protein from protein nitrogen.', 'The total protein found in food tables is rarely calculated from protein nitrogen. <PROCNT> is the appropriate tagname for total protein in most cases.')
   ('PROCNT', 'protein, total; calculated from total nitrogen', 'g', 'EGP, NE, EA FAO  conversion factor from a table in the FAO Nutritional Studies No. 24 (?), reprinted in the World Health Organization Technical Report Series No. 522 (?) Tables: MW, DAN USDA  conversion factor from a table in the United States Department of Agriculture Handbook No. 8 (?) Tables: USDA 203 STD  standard conversion factor of 6.25, not specific for the type of food.  (If this keyword is used, the 6.25 conversion factor should not be listed with the secondary tagname <XN>.) Tables: SFK, IND, PRC The following secondary tagname may be used to identify the specific conversion factor used when a keyword other than STD is present, or instead of a keyword (see above). <XN>  conversion factor for calculating total protein from total nitrogen', NULL, 'Following are the available keywords that can be used as the second value for the <PROCNT> tagname: JONES  conversion factor originally derived by Jones (?)', 'The 3.2 g/100 g of protein in cow\'s milk which is listed in the Nutritive Value of Indian Foods was calculated from total nitrogen using the 6.25 conversion factor. Therefore, the protein value would be listed using the <PROCNT> tagname and the STD keyword: <PROCNT> 3.2 STD </PROCNT> The 3.3 g/100 g of protein in cow\'s milk which is listed in McCance and Widdowson was calculated from total nitrogen using a 6.38 conversion factor.  This factor was obtained from the FAO publication. Therefore, the protein value would be listed using the <PROCNT> tagname, the FAO keyword, and the <XN> secondary tagname: <PROCNT> 3.3 FAO <XN> 6.38 </PROCNT> As a hypothetical example, if a value of 0.3 g/100 g of protein in watermelon seeds were calculated from total nitrogen using the conversion factor 5.30, and this value had not been taken from one of the tables identified by the list of keywords, the protein value would be listed using the <PROCNT> tagname in the following manner: <PROCNT> 0.3 <XN> 5.30 </PROCNT>', 'Three pieces of data are associated with the tagname <PROCNT>.  The first is the quantity of total protein; the second is a keyword which identifies the source of the conversion factor used to calculate the total protein from total nitrogen; and the third is the actual conversion factor used.  If possible, all three pieces of data should be included with <PROCNT>.  However, it is acceptable to include only the keyword or the conversion factor (rather than both) with the total protein value if one or the other is unknown.  If the conversion factor used was generated from a source other than one of those identified by the available keywords, the conversion factor should be listed without any keyword information.', 'In these examples, </PROCNT> is an end-tag required in interchange format to indicate the end of the information about protein calculated from total nitrogen. See the INFOODS Data Interchange Handbook for details on interchange format.')
   ('PROPAC', 'propionic acid', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('PROPLA', 'protein from plant sources', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('PSACALG', 'polysaccharides, algal', 'g', NULL, NULL, NULL, NULL, 'Includes carageenan, agar, and alginates.', NULL)
   ('PSACNC', 'polysaccharides, non-cellulosic', 'g', 'SWD', NULL, NULL, NULL, 'Includes hemicellulose, pectin, gums, algal polysaccharides, and mucilages.', NULL)
   ('PSACNCI', 'polysaccharides, non-cellulosic, water-insoluble', 'g', 'SWD', NULL, NULL, NULL, NULL, NULL)
   ('PSACNCS', 'polysaccharides, non-cellulosic, water-soluble', 'g', 'SWD', NULL, NULL, NULL, NULL, NULL)
   ('PSACNS', 'polysaccharides, non-starch', 'g', NULL, NULL, NULL, NULL, 'Includes non-cellulosic polysaccharides and cellulose.', NULL)
   ('PSACNSI', 'polysaccharides, non-starch, water- insoluble', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('PSACNSS', 'polysaccharides, non-starch, water- soluble', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('PURAC', 'polyuronic acids', 'mg', 'SFK, DAN', NULL, NULL, NULL, NULL, NULL)
   ('PURN', 'purines', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('PYRUAC', 'pyruvic acid', 'mg', 'USDA 247, SFK', NULL, NULL, NULL, NULL, NULL)
   ('PYRXL', 'pyridoxal', 'mg', 'USDA 412', NULL, NULL, NULL, 'Vitamin B-6 aldehyde form.', NULL)
   ('PYRXM', 'pyridoxamine', 'mg', 'USDA 413', NULL, NULL, NULL, 'Vitamin B-6 amine form.', NULL)
   ('PYRXN', 'pyridoxine', 'mg', 'USDA 411, EA', NULL, NULL, NULL, 'Vitamin B-6 alcohol form.', NULL)
   ('QUINAC', 'quinic acid', 'mg', 'USDA 248, SFK', NULL, NULL, NULL, NULL, NULL)
   ('RAFS', 'raffinose', 'g', 'SFK', NULL, NULL, NULL, 'Not available for humans.', NULL)
   ('RAFSM', 'Raffinose, expressed in monosaccharide equivalents', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('RB', 'Rubidium', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('RETAL', 'retinal', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('RETALD', 'retinaldehyde', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('RETOL', 'retinol', 'mcg', 'USDA 319, MW, NE, EA, DAN, SWD', 'preformed vitamin A', NULL, NULL, 'All-trans retinol only.', NULL)
   ('RETOL13', '13-cis retinol', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('RHAFB', 'rhamnose in dietary fibre', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('RHAS', 'rhamnose', 'g', NULL, NULL, NULL, NULL, 'Includes only the free sugar.', NULL)
   ('RIBF', 'riboflavin', 'mg', 'USDA 405, SFK, MW, ETH, IND, NE, EA, PRC, DAN, SWD', 'Vitamin B-2; riboflavine.', NULL, NULL, NULL, NULL)
   ('RIBS', 'ribose', 'g', NULL, NULL, NULL, NULL, 'D-ribose only; includes only the free monosaccharide.', NULL)
   ('S', 'sulphur', 'mg', 'USDA 308, MW, IND', NULL, NULL, NULL, NULL, NULL)
   ('SALAC', 'salicylic acid', 'mg', 'USDA 249', NULL, NULL, NULL, NULL, NULL)
   ('SB', 'Antimony', 'mcg', 'NZ', NULL, NULL, NULL, NULL, NULL)
   ('SE', 'selenium, total', 'mcg', 'USDA 317, SFK, EA, PRC, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('SEIO', 'selenium, inorganic', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('SEO', 'selenium, organic', 'mcg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('SER', 'serine', 'mg', 'USDA 518, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-serine.', NULL)
   ('SEROTN', 'serotonin', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('SHIKAC', 'shikimic acid', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('SI', 'silicon', 'mcg', 'USDA 378, SFK, PRC', NULL, NULL, NULL, NULL, NULL)
   ('SITSTR', 'sitosterol', 'mg', 'USDA 641, SFK', NULL, NULL, NULL, 'Beta-sitosterol only.', NULL)
   ('SN', 'tin', 'mcg', 'USDA 385, SFK', NULL, NULL, NULL, NULL, NULL)
   ('SOLO', 'Other solids', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('SORTL', 'sorbitol', 'mg', 'USDA 261, SFK', NULL, NULL, NULL, NULL, NULL)
   ('SPISTR', 'spinasterol', 'mg', 'USDA 650, FRN', NULL, NULL, NULL, 'Alpha-spinasterol only.', NULL)
   ('SR', 'strontium', 'mcg', 'USDA 380', NULL, NULL, NULL, NULL, NULL)
   ('STARCH', 'starch, total', 'g', 'USDA 209, SFK, DAN, SWD', NULL, NULL, NULL, 'The sum of all polysaccharides yielding glucose after hydrolysis with suitable enzymes; includes amylose, amylopectin, glycogen, and dextrins.', NULL)
   ('STARCHM', 'starch, total; expressed in monosaccharide equivalents', 'g', 'MW', NULL, NULL, NULL, 'The sum of all polysaccharides yielding glucose after hydrolysis with suitable enzymes; includes amylose, amylopectin, glycogen, and dextrins.', NULL)
   ('STARES', 'starch, resistant', 'g', NULL, 'retrograded starch', NULL, NULL, NULL, NULL)
   ('STAS', 'stachyose', 'g', 'SFK', NULL, NULL, NULL, 'Not available for humans.', NULL)
   ('STERFRE', 'sterols, free', 'mg', 'USDA 660, SFK', NULL, NULL, NULL, NULL, NULL)
   ('STERT', 'sterols, total', 'mg', 'USDA 634, SFK', NULL, NULL, NULL, 'Non-specific colorimetric method or sum of cholesterol and phytosterols.', NULL)
   ('STID7', 'delta 7-stigmasterol', 'mg', 'USDA 638, SFK', NULL, NULL, NULL, 'Values reported as ``stigmasterol\'\' in food tables are usually a measure of the delta 7 form only.', NULL)
   ('SUCAC', 'succinic acid', 'mg', 'USDA 250, SFK', NULL, NULL, NULL, NULL, NULL)
   ('SUCS', 'sucrose', 'g', 'USDA 210, SFK, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('SUCSM', 'sucrose; expressed in monosaccharide equivalents', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('SUGAR', 'sugars, total', 'g', 'USDA 269, SFK, DAN, SWD', NULL, NULL, NULL, 'Sum of free monosaccharides and disaccharides.', NULL)
   ('SUGARM', 'sugars, total; expressed in monosaccharide equivalents', 'g', 'MW', NULL, NULL, NULL, 'Sum of free monosaccharides and disaccharides expressed in monosaccharide equivalents.', NULL)
   ('SUGIN', 'invert sugar', 'g', 'SFK', NULL, NULL, NULL, 'Obsolete.', NULL)
   ('SUGNRD', 'sugars, non-reducing', 'g', 'USDA 270, SFK', NULL, NULL, NULL, 'Obsolete.', NULL)
   ('SUGRD', 'sugars, reducing', 'g', 'USDA 274, SFK', NULL, NULL, NULL, 'Obsolete.', NULL)
   ('TAN', 'tannins', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('TARAC', 'tartaric acid', 'mg', 'USDA 251, SFK', NULL, NULL, NULL, NULL, NULL)
   ('TAU', 'taurine', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('TGLY', 'triglycerides, total', 'g', 'USDA 657', NULL, NULL, NULL, NULL, NULL)
   ('THEBRN', 'theobromine', 'mg', 'USDA 263, SFK', NULL, NULL, NULL, NULL, NULL)
   ('THIA', 'thiamin', 'mg', 'USDA 404, SFK, MW, ETH, IND, NE, EA, PRC, DAN, SWD', 'vitamin B-1; aneurin; thiamine', NULL, NULL, NULL, NULL)
   ('THR', 'threonine', 'mg', 'USDA 502, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-threonine.', NULL)
   ('TOCPHA', 'alpha-tocopherol', 'mg', 'USDA 323, SFK, DAN, SWD', NULL, NULL, NULL, NULL, NULL)
   ('TOCPHA_ADDED', 'alpha-tocopherol added', 'mg', 'USDA 573', NULL, NULL, NULL, NULL, NULL)
   ('TOCPHB', 'beta-tocopherol', 'mg', 'USDA 341, SFK', NULL, NULL, NULL, NULL, NULL)
   ('TOCPHD', 'delta-tocopherol', 'mg', 'USDA 343, SFK', NULL, NULL, NULL, NULL, NULL)
   ('TOCPHG', 'gamma-tocopherol', 'mg', 'USDA 342, SFK', NULL, NULL, NULL, NULL, NULL)
   ('TOCPHT', 'Total tocopheral', 'mcg', 'USDA (nutrient number?)', NULL, NULL, NULL, NULL, NULL)
   ('TOCTRA', 'alpha-tocotrienol', 'mg', 'USDA 344, SFK, DAN', NULL, NULL, NULL, NULL, NULL)
   ('TOCTRB', 'beta-tocotrienol', 'mg', 'USDA 345, SFK', NULL, NULL, NULL, NULL, NULL)
   ('TOCTRD', 'delta-tocotrienol', 'mg', 'USDA 347', NULL, NULL, NULL, NULL, NULL)
   ('TOCTRG', 'gamma-tocotrienol', 'mg', 'USDA 346, SFK', NULL, NULL, NULL, NULL, NULL)
   ('TRP', 'tryptophan', 'mg', 'USDA 501, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-tryptophan.', NULL)
   ('TRYPN', 'tryptamine', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('TYR', 'tyrosine', 'mg', 'USDA 509, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-tyrosine.', NULL)
   ('UNSAP', 'unsaponifiable matter', 'g', 'USDA 643, EA', NULL, NULL, NULL, NULL, NULL)
   ('V', 'vanadium', 'mcg', 'USDA 389, SFK', NULL, NULL, NULL, NULL, NULL)
   ('VAL', 'valine', 'mg', 'USDA 510, SFK, ETH, NE, EA, DAN, SWD', NULL, NULL, NULL, 'Includes only L-valine.', NULL)
   ('VERS', 'verbascose', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('VITA', 'vitamin A; calculated by summation of the vitamin A activities of retinol and the active carotenoids', 'mcg.  The value for <VITA> may be expressed in international units instead of the default unit of micrograms.  International units are not preferred; however, if they are used, IU must be explicitly stated with the secondary tagname <UNIT/>.', 'USDA 392 and 318, ETH, IND, DAN', 'retinol equivalents', NULL, NULL, 'Total vitamin A activity = mcg retinol + 1/6 mcg beta-carotene + 1/12 mcg other provitamin A carotenoids.', 'It would be confusing and would imply additional information that does not exist if two <VITA> values, i.e., one expressed in mcg and the other expressed in IU, were included for a single food item when one value has simply been calculated from the other using the following conversion equation:  1 retinol equivalent = 3.33 IU vitamin A activity from retinol = 10 IU vitamin A activity from beta-carotene.  Consequently, one or the other should be used, but not both.')
   ('VITA-', 'vitamin A; method of determination unknown', 'mcg.  The value for <VITA-> may be expressed in international units instead of the default unit of micrograms. International units are not preferred; however, if they are used, IU must be explicitly stated with the secondary tagname <UNIT/>.', NULL, NULL, NULL, NULL, 'The <VITA-> tagname should be used if it is not known whether the vitamin A value was determined by bioassay or by calculation.', NULL)
   ('VITAA', 'vitamin A; determined by bioassay', 'IU', NULL, NULL, NULL, NULL, NULL, NULL)
   ('VITAACT', 'vitamin A acetate', 'mcg', 'USDA 325', NULL, NULL, NULL, NULL, NULL)
   ('VITAPAL', 'vitamin A palmitate', 'mcg', 'USDA 326', NULL, NULL, NULL, NULL, NULL)
   ('VITB12', 'vitamin B-12', 'mcg', 'USDA 418, SFK, MW, ETH, IND, EA, PRC, DAN, SWD', 'cobalamin', NULL, NULL, 'Includes all the active forms of vitamin B-12 in food.', NULL)
   ('VITB12_ADDED', 'vitamin B-12 added', 'mcg', 'USDA 578', 'cobalamin', NULL, NULL, NULL, NULL)
   ('VITB6-', 'vitamin B-6, total; method of determination unknown variable', 'mg', NULL, NULL, NULL, NULL, 'The <VITB6-> tagname should be used if it is not known whether the vitamin B-6 value was determined by analysis or by calculation.', NULL)
   ('VITB6A', 'vitamin B-6, total; determined by analysis', 'mg', 'USDA 415, MW', NULL, NULL, NULL, NULL, NULL)
   ('VITB6C', 'vitamin B-6, total; calculated by summation', 'mg', 'USDA 414, SFK, MW, DAN', NULL, NULL, NULL, 'Pyridoxal plus pyridoxamine plus pyridoxine.', NULL)
   ('VITC', 'vitamin C', 'mg', 'USDA 401, SFK, MW, ETH, IND, NE, EA, PRC, DAN', 'ascorbic acid; ascorbate  (Note that these terms are not true synonyms but are often found in food tables to refer to vitamin C.)', NULL, NULL, 'L-ascorbic acid plus L- dehydroascorbic acid.', NULL)
   ('VITD', 'vitamin D; calculated by summation of ergocalciferol and cholecalciferol', 'mcg.  The value for <VITD> may be expressed in international units instead of the default unit of micrograms.  International units are not preferred; however, if they are used, IU must be explicitly stated with the secondary tagname <UNIT/>.', 'USDA 324, MW', 'calciferol', NULL, NULL, 'Ergocalciferol plus cholecalciferol.', 'It would be confusing and would imply additional information that does not exist if two <VITD> values, i.e., one expressed in mcg and the other expressed in IU, were included for a single food item when one value has simply been calculated from the other using the conversion equation: 1 mcg vitamin D = 40 IU. Consequently, one or the other should be used, but not both.')
   ('VITD-', 'vitamin D; method of determination unknown or variable', 'mcg.  The value for <VITD-> may be expressed in international units instead of the default unit of micrograms. International units are not preferred; however, if they are used, IU must be explicitly stated with the secondary tagname <UNIT/>.', NULL, NULL, NULL, NULL, 'The <VITD-> tagname should be used if it is not known whether the vitamin D value was determined by bioassay or by calculation.', 'It would be confusing and would imply additional information that does not exist if two <VITD-> values, i.e., one expressed in mcg and the other expressed in IU, were included for a single food item when one value has simply been calculated from the other using the conversion equation: 1 mcg vitamin D = 40 IU.  Consequently, one or the other should be used, but not both.')
   ('VITDA', 'vitamin D; determined by bioassay', 'IU', 'MW', 'calciferol', NULL, NULL, NULL, NULL)
   ('VITE', 'vitamin E; calculated by summation of the vitamin E activities of the active tocopherols and tocotrienols; expressed as alpha-tocopherol equivalents', 'mg.  The value for <VITE> may be expressed in international units instead of the default unit of milligrams. International units are not preferred; however, if they are used, IU must be explicitly stated with the secondary tagname <UNIT/>.', 'USDA 340 MW  conversion factors cited by McCance and Widdowson (?), pages 13 and 14.  These values are not used in the vitamin E values in that table. alpha-tocopherol = 1.00 beta-tocopherol = 0.30 gamma-tocopherol = 0.15 alpha-tocotrienol = 0.30 Tables: MW RDA  conversion factors reported in the ninth edition of the Recommended Dietary Allowances for the United States (?) alpha-tocopherol = 1.00 beta-tocopherol = 0.50 gamma-tocopherol = 0.10 alpha-tocotrienol = 0.30 If none of the above keywords apply, the actual conversion factors used to calculate vitamin E should be listed using the following secondary tagnames: <XATP> alpha-tocopherol conversion factor <XBTP> beta-tocopherol conversion factor <XGTP> gamma-tocopherol conversion factor <XDTP> delta-tocopherol conversion factor <XATT> alpha-tocotrienol conversion factor <XBTT> beta-tocotrienol conversion factor <XGTT> gamma-tocotrienol conversion factor', NULL, 'The available keywords for describing the conversion factors used for calculating vitamin E in alpha-tocopherol equivalents are listed below: USDA  United States Department of Agriculture conversion factors as reported by McLaughlin & Weihrauch (?) alpha-tocopherol = 1.00 beta-tocopherol = 0.40 gamma-tocopherol = 0.10 delta-tocopherol = 0.01 alpha-tocotrienol = 0.30 beta-tocotrienol = 0.05 gamma-tocotrienol = 0.01', 'The 0.10 mg/100 g vitamin E value for fresh, whole cow\'s milk in the McCance and Widdowson food table represents alpha- tocopherol only.  Consequently, the value 0.10 would be shown with the <TOCPHA> tagname, not the <VITE> tagname and the associated keyword: <TOCPHA> 0.10 </TOCPHA> If a vitamin E value of 0.12, expressed in alpha-tocopherol equivalents, were calculated for whole cow\'s milk from the alpha-tocopherol, beta-tocopherol, gamma- tocopherol, and alpha-tocotrienol values, and the conversion factors used did not conform to any of the factors described by the available keywords, the vitamin E value would be listed using the <VITE> tagname and the <XBTP>, <XGTP>, and <XATT> secondary tagnames: <VITE> 0.12 <XBTP> 0.4 <XGTP> 0.1 <XATT> 0.25 </VITE>', 'In addition to a value for the quantity of vitamin E expressed as alpha- tocopherol equivalents, <VITE> includes a description or listing of the conversion factors used to calculate this vitamin E value from the active tocopherols and tocotrienols.  The conversion factors may be described by a keyword or may be listed using secondary tagnames within <VITE>. (More than one <VITE> tagname may exist for a single food item if the values were calculated from the active tocopherols and tocotrienols using different conversion factors.)', 'In these examples, </VITE> and </TOCPHA> are end-tags required in interchange format to indicate the end of the vitamin E information.  See the INFOODS Data Interchange Handbook for details on interchange format.')
   ('VITE-', 'vitamin E, method of determination unknown or variable; expressed as alpha- tocopherol equivalents.', 'mg.  The value for <VITE-> may be expressed in international units instead of the default unit of milligrams.  International units are not preferred; however, if they are used, IU must be explicitly stated with the secondary tagname <UNIT/>.', NULL, NULL, NULL, NULL, 'The <VITE-> tagname should be used if it is not known whether the vitamin E value was determined by bioassay or by calculation.  It should also be used if it is known that the vitamin E value was determined by calculation but the conversion factors used in the calculation are not known.', NULL)
   ('VITEA', 'vitamin E; determined by bioassay', 'IU', NULL, NULL, NULL, NULL, 'Rarely used, not in major tables.', NULL)
   ('VITK', 'vitamin K', 'mcg', 'SFK, DAN, SWD', NULL, NULL, NULL, 'Vitamin K-1 plus vitamin K- 2.', NULL)
   ('WATER', 'water', 'g', 'USDA 255, SFK, MW, ETH, EGP, IND, NE, EA, PRC, DAN, SWD', 'moisture', NULL, NULL, NULL, NULL)
   ('WAX', 'wax, total', 'mg', 'USDA 661', 'wax esters', NULL, NULL, NULL, NULL)
   ('WHEY', 'whey protein', 'mg', 'SFK', NULL, NULL, NULL, NULL, NULL)
   ('XYLFB', 'xylose in dietary fibre', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
   ('XYLN', 'xylan', 'g', NULL, NULL, NULL, NULL, NULL, NULL)
   ('XYLS', 'xylose', 'g', 'SFK', NULL, NULL, NULL, 'D-xylose only; includes only the free monosaccharide.', NULL)
   ('XYLTL', 'xylitol', 'mg', 'SF', NULL, NULL, NULL, NULL, NULL)
   ('ZEA', 'zeaxanthin', 'mcg', 'USDA', NULL, NULL, NULL, NULL, NULL)
   ('ZN', 'zinc', 'mg', NULL, NULL, NULL, NULL, NULL, NULL)
